export const suggestions_list = [
    { "location": "Canmore", "type": "Chalet rentals" },
    { "location": "Benalmádena", "type": "Flat rentals" },
    { "location": "Marbella", "type": "Villa rentals" },
    { "location": "Mijas", "type": "House rentals" },
    { "location": "Prescott", "type": "Cottage rentals" },
    { "location": "Scottsdale", "type": "Mansion rentals" },
    { "location": "Tucson", "type": "Pet-friendly rentals" },
    { "location": "Jasper", "type": "Cabin rentals" },
    { "location": "Mountain View", "type": "Family-friendly rentals" },
    { "location": "Devonport", "type": "Cottage rentals" },
    { "location": "Mallacoota", "type": "Pet-friendly rentals" },
    { "location": "Ibiza", "type": "Holiday rentals" },
    { "location": "Anaheim", "type": "Flat rentals" },
    { "location": "Monterey", "type": "Flat rentals" },
    { "location": "Paso Robles", "type": "House rentals" },
    { "location": "Santa Barbara", "type": "Apartment rentals" },
    { "location": "Sonoma", "type": "Pet-friendly rentals" },
    { "location": "La Serena", "type": "Beachfront rentals" },
    { "location": "Dubai", "type": "Beach house rentals" },
    { "location": "Birmingham", "type": "House rentals" },
    { "location": "Brighton Beach", "type": "Apartment rentals" },
    { "location": "Bude", "type": "Holiday rentals" },
    { "location": "Newcastle upon Tyne", "type": "Holiday rentals" },
    { "location": "Padstow", "type": "House rentals" },
    { "location": "South West England", "type": "Cabin rentals" },
    { "location": "Whitby", "type": "Cottage rentals" },
    { "location": "Fort Myers", "type": "Villa rentals" },
]